site_name: FastAPI Admin
site_url: https://fastapi-admin.github.io/fastapi-admin
repo_url: https://github.com/fastapi-admin/fastapi-admin/tree/v1
site_description: Fast Admin Dashboard based on fastapi and tortoise-orm
repo_name: fastapi-admin/fastapi-admin
site_author: long2ice
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
nav:
  - index.md
  - tutorial.md
  - content.md
extra:
  version:
    provider: mike
plugins:
  - mike:
      version_selector: true
